### ISSUE TITLE
An async operation was not properly started. (0x80000019)

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#509]
Time: 02/19/2023 18:03:37
URL: 
Hostname: LAPTOP-O6PR5OGM
Status Code: 
Type: System.Runtime.InteropServices.COMException
Source:    at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialogMethods.ShowAsync(IObjectReference _obj)
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at StoryBuilder.ViewModels.ShellViewModel.Preferences()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
User: Sean Fager(SeanFager@OUTLOOK.com)

**Comment by terrycox** [comment]
Attaching log trace.

**Comment by terrycox** [comment]
[Async failure in Preferences Update.docx](https://github.com/storybuilder-org/StoryBuilder-2/files/10784155/Async.failure.in.Preferences.Update.docx)

**Comment by terrycox** [comment]
I queried Sean what he did in Preferences. His response:
"Make a backup when story opened" is deactivated and the 
autosave timer is set to 5 minutes. I didn't adjust the values during that session, though."

**Comment by terrycox** [comment]
Closed per PR #546
