### ISSUE TITLE
System.NullReference exception in SaveFileAs

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#553]
**Describe the bug**
System.NullReferenceException: Object reference not set to an instance of an object.
   at StoryCAD.ViewModels.ShellViewModel.VerifyReplaceOrCreate()
   at StoryCAD.ViewModels.ShellViewModel.SaveFileAs()

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

[NullReference exception in SaveFileAs.txt](https://github.com/storybuilder-org/StoryCAD/files/11452877/NullReference.exception.in.SaveFileAs.txt)

**Comment by terrycox** [comment]
Closed per PR #584
