### ISSUE TITLE
System.NullReferenceException on StoryOverview Autosave

### ISSUE THREAD

**Issue by terrycox** [storybuilder-org/StoryCAD#602]
**Describe the bug**
StoryCADLib  
Category: StoryCADLib.Services.Logging.LogService
User: seanf
Version 2.11.0.0
System.NullReferenceException: Object reference not set to an instance of an object.
   at StoryCAD.ViewModels.OverviewViewModel.SaveModel()
   at StoryCAD.ViewModels.ShellViewModel.SaveModel()
   at StoryCAD.ViewModels.ShellViewModel.SaveFile(Boolean autoSave)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
<html>
<body>

An error occurred trying to obtain window size data The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD)) |  
-- | --
=== System Info === CPU ARCH - X64 OS ARCH - X64 App ARCH - 64 bit .NET Ver - X64 Startup - 1358 ms Elmah Status - True Developer Status - False Windows 11 Build - 22621 Debugger Attached - False Touchscreen - False ProcessID - 8820 Core Count - 12 StoryCAD Version - Version: 2.11.0.0 === User Prefs === Name - John Doe Email - JDoe@Email.com Elmah Consent - True Theme - #FFD3D3D3 Accent Color - #FF0078D4 Last Version Prefs logged - Version: 2.11.0.0 Search Engine - DuckDuckGo AutoSave - True AutoSave Interval - 15 Backup - False Backup Interval - 5 Backup on open - False Project Dir - C:\StoryCAD Backup Dir - C:\Users\seanf\OneDrive\Documents\StoryCAD\Backups RecordPreferencesStatus - False
2023-07-10 07:34:12.8880 \| Info \| Invoking AutoSave. \|
2023-07-10 07:34:27.8837 \| Info \| Invoking AutoSave. \|
2023-07-10 07:34:42.8884 \| Info \| Invoking AutoSave. \|
2023-07-10 07:34:57.8888 \| Info \| Invoking AutoSave. \|
2023-07-10 07:35:12.8773 \| Info \| Invoking AutoSave. \|
2023-07-10 07:35:27.8841 \| Info \| Invoking AutoSave. \|
2023-07-10 07:35:42.8817 \| Info \| Invoking AutoSave. \|
2023-07-10 07:35:57.8871 \| Info \| Invoking AutoSave. \|
2023-07-10 07:36:12.8845 \| Info \| Invoking AutoSave. \|
2023-07-10 07:36:27.8816 \| Info \| Invoking AutoSave. \|
2023-07-10 07:36:42.8888 \| Info \| Invoking AutoSave. \|
2023-07-10 07:36:57.8811 \| Info \| Invoking AutoSave. \|
2023-07-10 07:37:12.8879 \| Info \| Invoking AutoSave. \|
2023-07-10 07:37:27.8764 \| Info \| Invoking AutoSave. \|
2023-07-10 07:37:42.8781 \| Info \| Invoking AutoSave. \|
2023-07-10 07:37:57.8778 \| Info \| Invoking AutoSave. \|
2023-07-10 07:38:12.8886 \| Info \| Invoking AutoSave. \|
2023-07-10 07:38:27.8854 \| Info \| Invoking AutoSave. \|
2023-07-10 07:38:42.8775 \| Info \| Invoking AutoSave. \|
2023-07-10 07:38:57.8759 \| Info \| Invoking AutoSave. \|
2023-07-10 07:39:12.8794 \| Info \| Invoking AutoSave. \|
2023-07-10 07:39:27.8890 \| Info \| Invoking AutoSave. \|
2023-07-10 07:39:42.8830 \| Info \| Invoking AutoSave. \|
2023-07-10 07:39:57.8743 \| Info \| Invoking AutoSave. \|
2023-07-10 07:40:12.8835 \| Info \| Invoking AutoSave. \|
2023-07-10 07:40:27.8778 \| Info \| Invoking AutoSave. \|
2023-07-10 07:40:42.8758 \| Info \| Invoking AutoSave. \|
2023-07-10 07:40:57.8835 \| Info \| Invoking AutoSave. \|
2023-07-10 07:41:12.8834 \| Info \| Invoking AutoSave. \|
2023-07-10 07:41:27.8790 \| Info \| Invoking AutoSave. \|
2023-07-10 07:41:42.8867 \| Info \| Invoking AutoSave. \|
2023-07-10 07:41:57.8873 \| Info \| Invoking AutoSave. \|
2023-07-10 07:42:12.8800 \| Info \| Invoking AutoSave. \|
2023-07-10 07:42:27.8818 \| Info \| Invoking AutoSave. \|
2023-07-10 07:42:42.8886 \| Info \| Invoking AutoSave. \|
2023-07-10 07:42:57.8814 \| Info \| Invoking AutoSave. \|
2023-07-10 07:43:12.8798 \| Info \| Invoking AutoSave. \|
2023-07-10 07:43:27.1654 \| Info \| TreeViewNodeClicked for Fish Story \|
2023-07-10 07:43:27.8755 \| Info \| Invoking AutoSave. \|
2023-07-10 07:43:42.8853 \| Info \| Invoking AutoSave. \|
2023-07-10 07:43:45.2404 \| Info \| OverviewViewModel.OnPropertyChanged: StoryIdea changed \|
2023-07-10 07:43:57.8878 \| Info \| Invoking AutoSave. \|
2023-07-10 07:43:57.8878 \| Info \| Initiating AutoSave backup. \|
2023-07-10 07:43:57.8878 \| Info \| AutoSave executing \|
2023-07-10 07:43:57.8878 \| Trace \| SaveModel Page type=StoryCAD.Views.OverviewPage \|
2023-07-10 07:43:57.8878 \| Error \| Exception in AutoSave \| Object reference not set to an instance of an object. at StoryCAD.ViewModels.OverviewViewModel.SaveModel()
at StoryCAD.ViewModels.ShellViewModel.SaveModel()
at StoryCAD.ViewModels.ShellViewModel.SaveFile(Boolean autoSave)
2023-07-10 07:43:57.9087 \| Error \| AutoSave failed \|
 
end

</body>
</html>

**Comment by Rarisma** [comment]
Closing due to lack of info.
#606 should increase the logging
