### ISSUE TITLE
Error writing file - see log

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#726]
Time: 04/28/2024 11:43:22
Application: 
Version: Version: 2.13.1
Severity: Error
URL:  :arrow_right:  :arrow_right: 
Error: `System.Runtime.InteropServices.COMException`
Source: System.Private.CoreLib
User: ray64
Hostname: DESKTOP-V2V9RUK

More details on [elmah.io](https://app.elmah.io/errorlog/search?logId=6e87ad13-67cd-460b-b72f-0866cc738d89&hidden=true&expand=true&filters=id:%22F0AB4BBDB071AB5E%22#searchTab)

**Comment by terrycox** [comment]
SystemInfo	
Error getting System Info,
Line 0	
2024-04-28 12:43:22.1285 | Error | Error writing file - see log |
Line 1	
2024-04-28 12:43:22.1285 | Info | AutoSave completed |
Line 2	
2024-04-28 12:43:37.1257 | Info | Invoking AutoSave. |
Line 3	
2024-04-28 12:43:52.1215 | Info | Invoking AutoSave. |
Line 4	
2024-04-28 12:43:52.1215 | Info | Initiating AutoSave backup. |
Line 5	
2024-04-28 12:43:52.1215 | Info | AutoSave executing |
Line 6	
2024-04-28 12:43:52.1215 | Trace | SaveModel Page type=StoryCAD.Views.ProblemPage |
Line 7	
2024-04-28 12:43:52.1215 | Info | In WriteModel, file=A Ramsgate Ghost Story.stbx |
Line 8	
2024-04-28 12:43:52.1386 | Error | Error writing file | at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 9	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() Description: ;RestrictedDescription: ;RestrictedErrorReference: ;RestrictedCapabilitySid: ;__RestrictedErrorObjectReference: ;__HasRestrictedLanguageErrorObject: False
Line 10	
2024-04-28 12:43:52.1386 | Error | Error writing file
Line 11	
Stack Trace:
Line 12	
at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 13	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() |
Line 14	
2024-04-28 12:43:52.1386 | Error | Error writing file - see log |
Line 15	
2024-04-28 12:43:52.1386 | Info | AutoSave completed |
Line 16	
2024-04-28 12:44:07.1521 | Info | Invoking AutoSave. |
Line 17	
2024-04-28 12:44:07.1521 | Info | Initiating AutoSave backup. |
Line 18	
2024-04-28 12:44:07.1521 | Info | AutoSave executing |
Line 19	
2024-04-28 12:44:07.1521 | Trace | SaveModel Page type=StoryCAD.Views.ProblemPage |
Line 20	
2024-04-28 12:44:07.1521 | Info | In WriteModel, file=A Ramsgate Ghost Story.stbx |
Line 21	
2024-04-28 12:44:07.1521 | Error | Error writing file | at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 22	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() Description: ;RestrictedDescription: ;RestrictedErrorReference: ;RestrictedCapabilitySid: ;__RestrictedErrorObjectReference: ;__HasRestrictedLanguageErrorObject: False
Line 23	
2024-04-28 12:44:07.1521 | Error | Error writing file
Line 24	
Stack Trace:
Line 25	
at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 26	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() |
Line 27	
2024-04-28 12:44:07.1521 | Error | Error writing file - see log |
Line 28	
2024-04-28 12:44:07.1658 | Info | AutoSave completed |
Line 29	
2024-04-28 12:44:22.1707 | Info | Invoking AutoSave. |
Line 30	
2024-04-28 12:44:33.1749 | Info | Displaying Conflict Finder tool dialog |
Line 31	
2024-04-28 12:44:33.2823 | Info | Loading Controls.ini data |
Line 32	
2024-04-28 12:44:33.2998 | Info | ConflictType Counts |
Line 33	
2024-04-28 12:44:33.2998 | Info | 8 ConflictType keys created |
Line 34	
2024-04-28 12:44:33.2998 | Info | 77 Total ConflictSubType keys created |
Line 35	
2024-04-28 12:44:33.2998 | Info | 280 Total ConflictSubType keys created |
Line 36	
2024-04-28 12:44:37.1779 | Info | Invoking AutoSave. |
Line 37	
2024-04-28 12:44:37.1779 | Info | Initiating AutoSave backup. |
Line 38	
2024-04-28 12:44:37.1779 | Info | AutoSave executing |
Line 39	
2024-04-28 12:44:37.1779 | Trace | SaveModel Page type=StoryCAD.Views.ProblemPage |
Line 40	
2024-04-28 12:44:37.1779 | Info | In WriteModel, file=A Ramsgate Ghost Story.stbx |
Line 41	
2024-04-28 12:44:37.2035 | Error | Error writing file | at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 42	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() Description: ;RestrictedDescription: ;RestrictedErrorReference: ;RestrictedCapabilitySid: ;__RestrictedErrorObjectReference: ;__HasRestrictedLanguageErrorObject: False
Line 43	
2024-04-28 12:44:37.2069 | Error | Error writing file
Line 44	
Stack Trace:
Line 45	
at StoryCAD.ViewModels.ShellViewModel.CreateProjectFile()
Line 46	
at StoryCAD.ViewModels.ShellViewModel.WriteModel() |
Line 47	
2024-04-28 12:44:37.2069 | Error | Error writing file - see log |
Line 48	
2024-04-28 12:44:37.2069 | Info | AutoSave completed |
Line 49	
Log	
end
