### ISSUE TITLE
Error in Print reports.

### ISSUE THREAD

**Issue by Rarisma** [storybuilder-org/StoryCAD#730]
Time: 05/20/2024 21:06:19
Application: 
Version: Version: 2.13.1
Severity: Error
URL:  :arrow_right:  :arrow_right: 
Error: `System.OverflowException`
Source: System.Private.CoreLib
User: Ethan
Hostname: LAPTOP-02HH2TRT

More details on [elmah.io](https://app.elmah.io/errorlog/search?logId=6e87ad13-67cd-460b-b72f-0866cc738d89&hidden=true&expand=true&filters=id:%22927D09FD27CE7500%22#searchTab)

**Comment by terrycox** [comment]
Log data:
Error getting System Info,
2024-05-20 22:03:03.2762 | Info | Invoking AutoSave. |
2024-05-20 22:03:03.2762 | Info | Initiating AutoSave backup. |
2024-05-20 22:03:03.2762 | Info | AutoSave executing |
2024-05-20 22:03:03.2762 | Trace | SaveModel Page type=StoryCAD.Views.FolderPage |
2024-05-20 22:03:03.2762 | Info | In WriteModel, file=Trial.stbx |
2024-05-20 22:03:03.4713 | Info | WriteModel successful |
2024-05-20 22:03:03.4713 | Info | AutoSave completed |
2024-05-20 22:03:18.4820 | Info | Invoking AutoSave. |
2024-05-20 22:03:33.4882 | Info | Invoking AutoSave. |
2024-05-20 22:03:48.4880 | Info | Invoking AutoSave. |
2024-05-20 22:04:03.4829 | Info | Invoking AutoSave. |
2024-05-20 22:04:18.4817 | Info | Invoking AutoSave. |
2024-05-20 22:04:32.6891 | Info | TreeViewNodeClicked for Aurelia |
2024-05-20 22:04:33.4845 | Info | Invoking AutoSave. |
2024-05-20 22:04:33.4845 | Info | Initiating AutoSave backup. |
2024-05-20 22:04:33.4845 | Info | AutoSave executing |
2024-05-20 22:04:33.4845 | Trace | SaveModel Page type=StoryCAD.Views.FolderPage |
2024-05-20 22:04:33.4845 | Info | In WriteModel, file=Trial.stbx |
2024-05-20 22:04:33.5933 | Info | WriteModel successful |
2024-05-20 22:04:33.5933 | Info | AutoSave completed |
2024-05-20 22:04:33.7612 | Info | TreeViewNodeClicked for Verdania |
2024-05-20 22:04:34.4170 | Info | TreeViewNodeClicked for Verdinium |
2024-05-20 22:04:48.6031 | Info | Invoking AutoSave. |
2024-05-20 22:05:03.6133 | Info | Invoking AutoSave. |
2024-05-20 22:05:18.6046 | Info | Invoking AutoSave. |
2024-05-20 22:05:27.1862 | Info | TreeViewNodeClicked for Aurelia |
2024-05-20 22:05:27.6558 | Info | FolderViewModel.OnPropertyChanged: Notes changed |
2024-05-20 22:05:33.6067 | Info | Invoking AutoSave. |
2024-05-20 22:05:33.6067 | Info | Initiating AutoSave backup. |
2024-05-20 22:05:33.6067 | Info | AutoSave executing |
2024-05-20 22:05:33.6067 | Trace | SaveModel Page type=StoryCAD.Views.FolderPage |
2024-05-20 22:05:33.6067 | Info | In WriteModel, file=Trial.stbx |
2024-05-20 22:05:33.7817 | Info | WriteModel successful |
2024-05-20 22:05:33.7817 | Info | AutoSave completed |
2024-05-20 22:05:48.7890 | Info | Invoking AutoSave. |
2024-05-20 22:06:03.7954 | Info | Invoking AutoSave. |
2024-05-20 22:06:18.7896 | Info | Invoking AutoSave. |
2024-05-20 22:06:18.7896 | Info | Initiating AutoSave backup. |
2024-05-20 22:06:19.1617 | Error | Error in Print reports. | Value was either too large or too small for an Int32. at System.Convert.ToInt32(Double value)
at StoryCAD.Services.Reports.PrintReports.Print(String file)
2024-05-20 22:06:20.1265 | Error | Error in Print reports.
Stack Trace:
at System.Convert.ToInt32(Double value)
at StoryCAD.Services.Reports.PrintReports.Print(String file) |
2024-05-20 22:06:20.1265 | Info | AutoSave executing |
2024-05-20 22:06:20.1265 | Trace | SaveModel Page type=StoryCAD.Views.FolderPage |
2024-05-20 22:06:20.1265 | Info | In WriteModel, file=Trial.stbx |
2024-05-20 22:06:20.2418 | Info | WriteModel successful |
2024-05-20 22:06:20.2422 | Info | AutoSave completed |

**Comment by Rarisma** [comment]
Fixed via #732
